USE COMPANY_CONSTRAINTS;
SHOW TABLES;

-- DNUMBER: DEPARTMENT
DESC DEPARTAMENT;
DESC DEPT_LOCATIONS;

SELECT * FROM DEPARTAMENT;
SELECT * FROM DEPT_LOCATIONS;

-- RETIRA A AMBIGUIDADE ATRAVÉS DO ALIAS OU AS STATEMENT
SELECT DNAME, L.DLOCATION AS DEPARTAMENT_NAME
	FROM DEPARTAMENT AS D, DEPT_LOCATIONS AS L
	WHERE D.DNUMBER = L.DNUMBER;

SELECT CONCAT (FNAME, ' ', LNAME) AS EMPLOYEE FROM EMPLOYEE;

-- REGEXP '^TO'

-- EXPRESSÕES E ALIAS

-- RECOLHENDO O VALOR DO INSS-*
SELECT FNAME, LNAME, SALARY, SALARY*0.011 FROM EMPLOYEE;
SELECT FNAME, LNAME, SALARY, SALARY*0.011 AS INSS FROM EMPLOYEE;
SELECT FNAME, LNAME, SALARY, ROUND(SALARY*0.011,2) AS INSS FROM EMPLOYEE;

-- DEFINIR AUMENTO DE SALÁRIO PARA OS GERENTES QUE TRABALHAM NO PROJETO ASSOCIADO AO PRODUTOX
DESC PROJECT;
DESC WORKS_ON;

SELECT *
	FROM EMPLOYEE E, WORKS_ON AS W, PROJECT AS P
	WHERE(E.SSN=W.ESSN AND W.PNO=P.PNUMBER);
    
SELECT CONCAT(FNAME, ' ', LNAME) AS COMPLETE_NAME, SALARY, ROUND(SALARY*1.1,2) AS INCREASED_SALARY
	FROM EMPLOYEE E, WORKS_ON AS W, PROJECT AS P
	WHERE(E.SSN=W.ESSN AND W.PNO=P.PNUMBER AND P.PNAME='PRODUCTX');
    
-- DEFININDO ALIAS PARA LEGIBILIDADE DA CONSULTA
SELECT CONCAT(E.FNAME, ' ',  E.LNAME) AS EMPLOYEE_NAME, E.ADDRESS FROM EMPLOYEE E, DEPARTAMENT D
	WHERE D.DNAME = 'RESEARCH' AND D.DNUMBER=E.DNO;
    
-- LIKE E BETWEEN
SELECT * FROM EMPLOYEE;

SELECT CONCAT(FNAME, ' ', LNAME) COMPLETE_NAME, DNAME, ADDRESS AS DEPARTMENT_NAME FROM EMPLOYEE, DEPARTAMENT
	WHERE (DNO=DNUMBER AND ADDRESS LIKE '%HOUSTON%');
    
SELECT CONCAT(FNAME, ' ', LNAME) COMPLETE_NAME, ADDRESS FROM EMPLOYEE
	WHERE ADDRESS LIKE '%HOUSTON%';
    
SELECT FNAME, LNAME, SALARY FROM EMPLOYEE WHERE (SALARY > 30000 AND SALARY < 40000);

SELECT FNAME, LNAME FROM EMPLOYEE WHERE (SALARY BETWEEN 20000 AND 40000);

-- OPERADORES LÓGICOS
SELECT BDATE, ADDRESS FROM EMPLOYEE WHERE FNAME='JOHN' AND MINIT='B' AND LNAME='SMITH';

SELECT * FROM DEPARTAMENT WHERE DNAME='RESEARCH' OR DNAME='ADMINISTRATION';

SELECT FNAME, LNAME FROM EMPLOYEE, DEPARTAMENT WHERE DNAME='RESEARCH' AND DNUMBER=DNO;
SELECT CONCAT(FNAME, ' ', LNAME) AS COMPLETE_NAME FROM EMPLOYEE, DEPARTAMENT WHERE DNAME='RESEARCH' AND DNUMBER=DNO;
