-- explorando os campos ddl

SELECT NOW() AS TIMESTAMP;

CREATE DATABASE IF NOT EXISTS MANIPULATION;
USE MANIPULATION;

CREATE TABLE BANKACCOUNTS (
	ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
    AG_NUM INT NOT NULL,
    AC_NUM INT NOT NULL,
    SALDO FLOAT,
    CONSTRAINT IDENTIFICATION_ACCOUNT_CONSTRAINT UNIQUE (AG_NUM, AC_NUM)
);

INSERT INTO BANKACCOUNTS (AG_NUM, AC_NUM, SALDO) VALUES (156, 264358, 0);
SELECT * FROM BANKACCOUNTS;

ALTER TABLE BANKACCOUNTS ADD LIMITECREDITO FLOAT NOT NULL DEFAULT 500.00;
ALTER TABLE BANKACCOUNTS ADD EMAIL VARCHAR(60);
ALTER TABLE BANKACCOUNTS DROP EMAIL;
-- ALTER TABLE NOME_TABELA MODIFY COLUMN NOME_ATRIBUTO TIPO_DADOS CONDIÇÃO;
-- ALTER TABLE NOME_TABELA ADD CONSTRAINT NOME_CONSTRAINT CONDIÇÕES;

DESC BANKACCOUNTS;

CREATE TABLE BANKCLIENT(
	ID_CLIENT INT AUTO_INCREMENT,
    CLIENTACCOUNT INT,
    CPF CHAR(11) NOT NULL,
    RG CHAR(9) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDEREÇO VARCHAR(100) NOT NULL,
    RENDA_MENSAL FLOAT,
    PRIMARY KEY (ID_CLIENT, CLIENTACCOUNT),
    CONSTRAINT FK_ACCOUNT_CLIENT FOREIGN KEY (CLIENTACCOUNT) REFERENCES BANKACCOUNTS(ID_ACCOUNT)
    ON UPDATE CASCADE
);

DROP TABLE BANKCLIENT;

ALTER TABLE BANKCLIENT ADD UFF CHAR(2) NOT NULL DEFAULT 'RJ';

INSERT INTO  BANKCLIENT (CLIENTACCOUNT, CPF, RG, NOME, ENDEREÇO, RENDA_MENSAL)VALUES(1, 12345678913, 123456789, 'FULANO', 'RUA DE LÁ', 6500.6);
SELECT * FROM BANKCLIENT;

UPDATE BANKCLIENT SET UFF='MG' WHERE NOME = 'FULANO';

CREATE TABLE BANKTRANSACTIONS(
	ID_TRANSACTION INT AUTO_INCREMENT PRIMARY KEY,
    OCORRENCIA DATETIME,
    STATUS_TRANSACTION VARCHAR(20),
    VALOR_TRANSFERIDO FLOAT,
    SOURCE_ACCOUNT INT,
    DESTINATION_ACCOUNT INT,
    CONSTRAINT FK_SOURCE_TRANSACTION FOREIGN KEY (SOURCE_ACCOUNT) REFERENCES
    BANKACCOUNTS(ID_ACCOUNT),
    CONSTRAINT FK_DESTINATION_TRANSACTION FOREIGN KEY (DESTINATION_ACCOUNT) REFERENCES
    BANKACCOUNTS(ID_ACCOUNT)
);

