-- EXPRESSÕES E CONCATENAÇÃO DE STRINGS

DESC DEPT_LOCATIONS;
SELECT * FROM DEPT_LOCATIONS;
-- RECUPERANDO INFORMAÇÕES DOS DEPARTAMENTOS PRESENTES EM STAFFORD
SELECT DNAME AS DEPARTMENT_NAME, MGR_SSN AS MANAGER, ADDRESS FROM DEPARTAMENT D, DEPT_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION='STAFFORD';
    
-- RECUPERANDO TODOS OS GERENTES QUE TRABALHAM EM STAFFORD
SELECT DNAME AS DEPARTMENT_NAME, CONCAT(FNAME, ' ', LNAME) AS MANAGER FROM DEPARTAMENT D, DEPT_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION='STAFFORD' AND MGR_SSN=E.SSN;

DESC DEPARTAMENT;
-- RECUPERANDO TODOS OS GERENTES, DEPARTAMENTOS E SEUS NOMES
SELECT DNAME AS DEPARTMENT_NAME, CONCAT(FNAME, ' ', LNAME) AS MANAGER, DLOCATION FROM DEPARTAMENT D, DEPT_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND MGR_SSN=E.SSN;
    
-- RECUPERANDO TODOS OS GERENTES, DEPARTAMENTOS E SEUS NOMES
SELECT PNUMBER, DNUM, LNAME, ADDRESS, BDATE FROM DEPARTAMENT D, PROJECT P, EMPLOYEE E
	WHERE D.DNUMBER = P.DNUM AND P.PLOCATION='STAFFORD' AND MGR_SSN=E.SSN;

