-- FUNÇÕES E CLÁUSULAS DE AGRUPAMENTO

SELECT * FROM EMPLOYEE;
SELECT COUNT(*) FROM EMPLOYEE;

SELECT COUNT(*) FROM EMPLOYEE, DEPARTAMENT
	WHERE DNO=DNUMBER AND DNAME='RESEARCH';
    
SELECT DNO, COUNT(*) AS NUMBER_OF_EMPLOYEES, ROUND(AVG(SALARY),2) AS SALARY_AVG FROM EMPLOYEE
	GROUP BY DNO;
    
SELECT PNUMBER, PNAME, COUNT(*)
	FROM PROJECT, WORKS_ON
    WHERE PNUMBER=PNO
    GROUP BY PNUMBER, PNAME;

SELECT COUNT(DISTINCT SALARY) FROM EMPLOYEE;

SELECT SUM(SALARY) AS TOTAL_SAL, MAX(SALARY) AS MAX_SAL, MIN(SALARY) AS MINI_SAL, AVG(SALARY) AS AVG_SAL FROM EMPLOYEE;

-- JOIN SERÁ ABORDADO NO CURSO 5
SELECT SUM(SALARY), MAX(SALARY), MIN(SALARY), AVG(SALARY)
	FROM (EMPLOYEE JOIN DEPARTAMENT ON DNO=DNUMBER)
    WHERE DNAME='RESEARCH';
    
SELECT LNAME, FNAME
	FROM EMPLOYEE
	WHERE ( SELECT COUNT(*)
			FROM DEPENDENT
            WHERE SSN=ESSN)>=2;

-- GROUP BY

SHOW TABLES;
SELECT PNUMBER, PNAME, COUNT(*) AS NUMBER_OF_REGISTER, ROUND(AVG(SALARY),2) AS AVG_SALARY
	FROM PROJECT, WORKS_ON, EMPLOYEE
    WHERE PNUMBER=PNO AND SSN=ESSN
    GROUP BY PNUMBER, PNAME;

SELECT PNUMBER, PNAME, COUNT(*) AS NUMBER_OF_REGISTER, ROUND(AVG(SALARY),2) AS AVG_SALARY
	FROM PROJECT, WORKS_ON, EMPLOYEE
    WHERE PNUMBER=PNO AND SSN=ESSN
    GROUP BY PNUMBER
    ORDER BY AVG(SALARY) DESC;

-- GROUP BY E HAVING

SELECT PNUMBER, PNAME, COUNT(*)
	FROM PROJECT, WORKS_ON
    WHERE PNUMBER=PNO
    GROUP BY PNUMBER, PNAME
    HAVING COUNT(*)>2;

SELECT DNO, COUNT(*)
	FROM EMPLOYEE
    WHERE SALARY>30000
    GROUP BY DNO
    HAVING COUNT(*)>=2;

SELECT DNO AS DEPARTMENT, COUNT(*) AS NUMBEROFEMPLOYEES
	FROM EMPLOYEE
    WHERE SALARY>20000
		AND DNO IN (SELECT DNO FROM EMPLOYEE
					GROUP BY DNO
                    HAVING COUNT(*)>=2)
	GROUP BY DNO;
    

