-- JOIN COM MAIS DE TABELAS

DESC PROJECT;
-- PROJECT, WORKS_ON E EMPLOYEE
SELECT CONCAT(FNAME, ' ', LNAME) AS COMPLETE_NAME, DNO AS DEPTNUMBER, PNAME AS PROJECTNAME,
		PNO AS PROJECTNUMBER, PLOCATION AS LOCATION FROM EMPLOYEE
	INNER JOIN WORKS_ON ON SSN=ESSN
    INNER JOIN PROJECT ON PNO=PNUMBER
    WHERE PNAME LIKE 'PRODUCT%'
    ORDER BY PNUMBER;

-- DEPARTAMENT, DEPT_LOCATIONS, EMPLOYEE
SELECT DNUMBER, DNAME, CONCAT(FNAME, ' ', LNAME) AS MANAGER, SALARY, ROUND(SALARY*0.05,2) AS BONUS FROM DEPARTAMENT
	INNER JOIN DEPT_LOCATIONS USING(DNUMBER)
    INNER JOIN EMPLOYEE ON SSN=MGR_SSN
    GROUP BY DNUMBER;

-- DEPARTAMENT, PROJECT E EMPLOYEE

SELECT DNUMBER, DNAME, CONCAT(FNAME, ' ', LNAME) AS MANAGER, SALARY, ROUND(SALARY*0.05,2) AS BONUS FROM DEPARTAMENT
	INNER JOIN DEPT_LOCATIONS USING(DNUMBER)
    INNER JOIN EMPLOYEE ON SSN=MGR_SSN
    GROUP BY DNUMBER
    HAVING COUNT(*)>1;

SELECT DNUMBER, DNAME, CONCAT(FNAME, ' ', LNAME) AS MANAGER, SALARY, ROUND(SALARY*0.05,2) AS BONUS FROM DEPARTAMENT
	INNER JOIN DEPT_LOCATIONS USING(DNUMBER)
    INNER JOIN (DEPENDENT INNER JOIN EMPLOYEE ON SSN=ESSN) ON SSN=MGR_SSN
    GROUP BY DNUMBER;

-- OUTER JOIN

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPENDENT;

SELECT * FROM EMPLOYEE INNER JOIN DEPENDENT ON SSN=ESSN;
SELECT * FROM EMPLOYEE LEFT JOIN DEPENDENT ON SSN=ESSN;
