-- CASE STATEMENT

USE COMPANY_CONSTRAINTS;

SHOW TABLES;

SELECT FNAME, SALARY, DNO FROM EMPLOYEE;

-- DESABILITAR O SAFE MODE
UPDATE EMPLOYEE SET SALARY = 
	CASE
		WHEN DNO=5 THEN SALARY+ 2000
        WHEN DNO=4 THEN SALARY+ 1500
        WHEN DNO=1 THEN SALARY+ 3000
        ELSE SALARY + 0
	END;
