-- CLÁUSULAS DE ORDENAÇÃO
USE COMPANY_CONSTRAINTS;
SELECT * FROM EMPLOYEE ORDER BY FNAME, LNAME;

-- NOME DO DEPARTAMENTO, NOME DO GERENTE
SELECT DISTINCT D.DNAME, CONCAT(E.FNAME, ' ', E.LNAME) AS MANAGER, ADDRESS
	FROM DEPARTAMENT AS D, EMPLOYEE AS E, WORKS_ON AS W, PROJECT P
	WHERE (D.DNUMBER=E.DNO AND E.SSN=D.MGR_SSN AND W.PNO=P.PNUMBER)
    ORDER BY D.DNAME;

-- RECUPERO TODOS OS EMPREGADOS E SEUS PROJETOS EM ANDAMENTO
SELECT D.DNAME AS DEPARTMENT, CONCAT(E.FNAME, ' ', E.LNAME) AS EMPLOYEE, P.PNAME AS PROJECT_NAME, ADDRESS
	FROM DEPARTAMENT AS D, EMPLOYEE AS E, WORKS_ON AS W, PROJECT P
    WHERE (D.DNUMBER=E.DNO AND E.SSN=W.ESSN AND W.PNO=P.PNUMBER)
    ORDER BY D.DNAME DESC, E.FNAME ASC, E.FNAME ASC;
    
-- SELECT <ATTRIBUTE LIST>
-- FROM <TABLE LIST>
-- [ WHERE <CONDITION> ]
-- [ ORDER BY <ATTRIBUTE LIST> ];
