-- SUBQUERRIES

USE COMPANY_CONSTRAINTS;

SELECT * FROM EMPLOYEE;

SELECT DISTINCT PNUMBER FROM PROJECT
	WHERE PNUMBER IN
        (
			SELECT DISTINCT PNO
			FROM WORKS_ON, EMPLOYEE
            WHERE (ESSN=SSN AND LNAME='SMITH')
		)
        OR
        (
			SELECT PNUMBER
			FROM PROJECT, DEPARTAMENT, EMPLOYEE
			WHERE (MGR_SSN=SSN AND LNAME='SMITH' AND DNUM=DNUMBER)
        );

SELECT DISTINCT * FROM WORKS_ON
	WHERE (PNO, HOURS) IN (SELECT PNO, HOURS
							FROM WORKS_ON
                            WHERE ESSN=123456789);

-- CLÁUSULAS COM EXISTS E UNIQUE


-- QUAIS EMPLOYESS POSSUEM DEPENDENTES?
SELECT FNAME, LNAME FROM EMPLOYEE AS E
	WHERE EXISTS (SELECT * FROM DEPENDENT AS D
					WHERE E.SSN=D.ESSN);
                    
SELECT FNAME, LNAME FROM EMPLOYEE AS E
	WHERE EXISTS (SELECT * FROM DEPENDENT AS D
					WHERE E.SSN=D.ESSN AND RELATIONSHIP='DAUGHTER');

-- EMPREGADOS QUE NÃO POSSUEM DEPENDENTES
SELECT FNAME, LNAME FROM EMPLOYEE AS E
	WHERE NOT EXISTS (SELECT * FROM DEPENDENT AS D
					WHERE E.SSN=D.ESSN);

SELECT FNAME, LNAME FROM EMPLOYEE AS E
	WHERE EXISTS(SELECT * FROM DEPARTAMENT
					WHERE SSN=MGR_SSN);

SELECT FNAME, LNAME FROM EMPLOYEE AS E
	WHERE EXISTS(SELECT * FROM DEPENDENT AS D
					WHERE E.SSN=D.ESSN)
                    AND
				(SELECT * FROM DEPARTAMENT
					WHERE SSN=MGR_SSN);

-- RESOLVE A QUERY ACIMA
SELECT E.FNAME, E.LNAME FROM EMPLOYEE AS E, DEPARTAMENT D
	WHERE (E.SSN=D.MGR_SSN) AND EXISTS (SELECT * FROM DEPENDENT AS D WHERE E.SSN=D.ESSN);
    
SELECT FNAME, LNAME FROM EMPLOYEE
	WHERE (SELECT COUNT(*) FROM DEPENDENT WHERE SSN=ESSN)>=2;
    
SELECT DISTINCT ESSN, PNO FROM WORKS_ON WHERE PNO IN (1,2,3);
