-- UNION, EXCEPT E INTERSECT

CREATE DATABASE TESTE;
USE TESTE;

CREATE TABLE R(
	A CHAR(2)
);

CREATE TABLE S(
	A CHAR(2)
);

INSERT INTO R(A) VALUES('A1'),('A2'),('A2'),('A3');
INSERT INTO S(A) VALUES('A1'),('A1'),('A2'),('A3'),('A4'),('A5');

SELECT * FROM R;
SELECT * FROM S;

-- EXCEPT -> NOT IN
SELECT * FROM S WHERE A NOT IN (SELECT A FROM R);

-- INTERSECT
SELECT DISTINCT R.A FROM R WHERE R.A IN (SELECT S.A FROM S);

-- UNION
(SELECT DISTINCT R.A FROM R) UNION (SELECT DISTINCT S.A FROM S);
(SELECT R.A FROM R) UNION (SELECT S.A FROM S);
